version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - persist_to_workspace:
        root: ~/
        paths:
          - project
  test-node8:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
        at: ~/
      - run: npm test
  test-node9:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
        at: ~/
      - run: npm test
  test-node10:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
        at: ~/
      - run: npm test
  test-node11:
    docker:
      - image: circleci/node:11
    steps:
      - attach_workspace:
        at: ~/
      - run: npm test
  test-node12:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
        at: ~/
      - run: npm test

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build
      - test-node8:
        requires:
          - build
      - test-node9
        requires:
          - build
      - test-node10
        requires:
          - build
      - test-node11
        requires:
          - build
      - test-node12
        requires:
          - build
